version: "3"

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=monorepo
      - MYSQL_USER=adam
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
